theme: jekyll-theme-minimal
title: Colin J. Burke, PhD
description: NSF AAPF Postdoctoral Fellow, Department of Astronomy, Yale University
logo: https://github.com/user-attachments/assets/629e4aac-af87-44ec-8153-477cfeb2b039
